FROM docker.io/library/alpine:latest
RUN apk add --no-cache bash curl

# Copy our Test Composer scripts to the folder where Antithesis will find them.
# Change the scripts' permissions to allow them to be executed.
COPY test_composer /opt/antithesis/test/v1/helloantithesis
RUN chmod -R +x /opt/antithesis/test/v1/helloantithesis

CMD ["sleep", "infinity"]